<sect1 id="zend.exception.using">

    <title>Utilizzo delle eccezioni</title>

    <para>
        Tutte le eccezioni lanciate dalle classi del Framework Zend dovrebbero estendere la classe base Zend_Exception.
    </para>

    <example id="zend.exception.using.example">
        <title>Gestione di un'eccezione</title>
        <para>
            Il codice seguente dimostra come gestire un'eccezione lanciata all'interno di una classe del Framework Zend:
        </para>
        <programlisting role="php"><![CDATA[
try {
    // La chiamata a Zend_Loader::loadClass() con una classe non esistente
    // causa il lancio di un'eccezione in Zend_Loader
    Zend_Loader::loadClass('classenonesistente');
} catch (Zend_Exception $e) {
    echo "Catturata eccezione: " . get_class($e) . "\n";
    echo "Messaggio: " . $e->getMessage() . "\n";
    // Altro codice necessario per gestire l'errore
}
]]>
        </programlisting>
    </example>

    <para>
        The documentation for each Zend Framework
        component and class will contain specific information on which methods
        throw exceptions, the circumstances that cause an exception to be thrown,
        and the class of all exceptions that may be thrown.
    </para>

    <para>
        La documentazione di ogni componente e classe del Framework Zend
        contiene informazioni specifiche su quali metodi lanciano un'eccezione,
        le circostanze che possono causare l'errore e le classi per tutte
        le eccezioni che possono essere lanciate.
    </para>

</sect1>
<!--
vim:se ts=4 sw=4 et:
-->